Add support for multiple font styles
simple-icons/simple-icons-font pull request #212
Opened 2024-09-11 15:09 UTC by LitoMore

Related to #222
Resolves #211

### Get a preview build

Download it from: [simple-icons-font-multi-styles.zip](https://github.com/user-attachments/files/18266580/simple-icons-font-multi-styles.zip)

### Changes

- This changed the default font style to the same aspect ratio as the icon. Users still can use the squared version with the `SimpleIcons-Squared.[ext]` font file
- Re-organized the font file locations since we added a new style
- Specify the `font-style` in the font SVG template

### Web browser preview

![](https://github.com/user-attachments/assets/50ab7ced-44c1-4c41-958f-93fe9fdf9738)

### Typeface preview

| Before | After |
|:-:|:-:|
|![](https://github.com/user-attachments/assets/2f326721-f378-4ab8-bf04-21860ed288b2)|![](https://github.com/user-attachments/assets/6077129d-c92a-4f72-a2e2-b1b92aafab65)| 

### File tree

```
font
├── simple-icons.css
├── simple-icons.min.css
├── simple-icons.json
├── simple-icons.min.json
├── SimpleIcons.eot
├── SimpleIcons-Fit.eot
├── SimpleIcons.otf
├── SimpleIcons-Fit.otf
├── SimpleIcons.svg
├── SimpleIcons-Fit.svg
├── SimpleIcons.ttf
├── SimpleIcons-Fit.ttf
├── SimpleIcons.woff
├── SimpleIcons-Fit.woff
├── SimpleIcons.woff2
└── SimpleIcons-Fit.woff2
```

2024-12-28 07:36 UTC, LitoMore commented
I think we build it to different font styles. For example:

- Simple Icons (Squared Viewbox)
	- Our current style
- Simple Icons (Actual Viewbox)
	- Use the viewbox with the same aspect ratio as the icon entity
- Simple Icons (Monospaced Viewbox)
	- The viewbox can only be a multiple of the unit width. It is designed for terminal emulators.

2025-01-12 23:18 UTC, mondeja commented
This seems like a breaking change to me. Can we prepare it for v15?

2025-01-12 23:21 UTC, LitoMore commented
> This seems like a breaking change to me. Can we prepare it for v15?

Sure. Let's convert it to draft.

2025-05-31 06:44 UTC, LitoMore commented
@mondeja Resolved conflicts and ready for review.

2025-05-31 07:13 UTC, mondeja commented
Would you mind to resolve conflicts again?

2025-05-31 07:25 UTC, mondeja requested changes
I think that the regular style should keep the old file name. Adding `-Regular` to the file name only confuses and adds a breaking change to most consumers of this library providing no benefits.

2025-05-31 07:32 UTC, LitoMore commented
> I think that the regular style should keep the old file name. Adding -Regular to the file name only confuses and adds a breaking change to most consumers of this library providing no benefits.

Good point. Do you have a good suggestion for the new style name? What about `Fit`?

2025-05-31 07:43 UTC, mondeja commented
> > I think that the regular style should keep the old file name. Adding -Regular to the file name only confuses and adds a breaking change to most consumers of this library providing no benefits.
> 
> Good point. Do you have a good suggestion for the new style name? What about `Fit`?

If it provides the same functionality than `viewbox=auto` in the CDN, probably `viewbox-auto` or `ViewboxAuto` or `viewbox=auto` or whatever, to maintain the same API. But I'm not totally sure if that would be better than `Fit` anyway, so as you want.

2025-05-31 07:57 UTC, LitoMore commented
Thanks for your thoughts. I think `auto-viewbox` is more for SVGs, and `fit` would be better for font style names.

I've kept the old icon style as Regular. And the new icon style is Fit.

It's ready for review now.

2025-05-31 08:09 UTC, mondeja requested changes
I'm probably not expressing myself correctly. What I was saying earlier is that I think that the generated directory structure should be like this:

```
font
├── Fit
│   ├── SimpleIcons-Fit.eot
│   ├── SimpleIcons-Fit.otf
│   ├── SimpleIcons-Fit.svg
│   ├── SimpleIcons-Fit.ttf
│   ├── SimpleIcons-Fit.woff
│   └── SimpleIcons-Fit.woff2
├── simple-icons.css
├── SimpleIcons.eot
├── SimpleIcons.json
├── simple-icons.min.css
├── SimpleIcons.min.json
├── SimpleIcons.otf
├── SimpleIcons.svg
├── SimpleIcons.ttf
├── SimpleIcons.woff
└── SimpleIcons.woff2
```

Instead of the one currently being generated, which is this:

```
font
├── eot
│   ├── SimpleIcons-Fit.eot
│   └── SimpleIcons-Regular.eot
├── otf
│   ├── SimpleIcons-Fit.otf
│   └── SimpleIcons-Regular.otf
├── simple-icons.css
├── SimpleIcons.json
├── simple-icons.min.css
├── SimpleIcons.min.json
├── svg
│   ├── SimpleIcons-Fit.svg
│   └── SimpleIcons-Regular.svg
├── ttf
│   ├── SimpleIcons-Fit.ttf
│   └── SimpleIcons-Regular.ttf
├── woff
│   ├── SimpleIcons-Fit.woff
│   └── SimpleIcons-Regular.woff
└── woff2
    ├── SimpleIcons-Fit.woff2
    └── SimpleIcons-Regular.woff2
```

For several reasons:

- Avoid the breaking change for consumers of needing to change the file used. This is a breaking change for most of them that does not offer benefits.
- Less directories.
- Less weird names in fonts.

2025-05-31 14:03 UTC, mondeja approved these changes
Much better. Thank you, this is great!

2025-05-31 14:04 UTC, merged